[package]
name = "dictd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "^1", features = ["rt-multi-thread", "net", "macros", "io-util", "fs"]}
tokio-util = { version = "*", features=["codec"] }
futures-util = "0.3.25"
futures = { version = "^0.3" }
regex = "1.7.1"
rayon = "1.6.1"
strum = "0.24"
serde = "^1"
toml = "^0.6"
strum_macros = "0.24"
egzreader = "2.0.4"
sqlite-zstd = {path = "../OtherAlien/sqlite-zstd" }
newline-converter = "0.2.2"

[profile.release]
opt-level = 3

[profile.fastprod]
inherits = "release"
opt-level = 1

[profile.fastdev]
inherits = "dev"
opt-level = 1

[profile.production]
inherits = "release"
lto = "fat"